apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: pe-demo-starter-golang
  title: PE Demo Starter Golang
  description: Template for the scaffolding of a golang service.
spec:
  owner: user:ankitwal
  type: service

  parameters:
    - title: Resource name
      required:
        - name
        - version
        - db_engine_major_version
        - default_db_instance_size
      properties:
        name:
          title: Name
          type: string
          description: Name scoped to the the component
          default: "rds"
          ui:options:
            rows: 5
        version:
          title: Version
          type: string
          description: Unique name of the component
          default: "v0.0.2-alpha"
          ui:options:
            rows: 5
        db_engine_major_version:
          title: DB Engine Major Version
          type: string
          description: The major version of the database engine
          default: "11"
          ui:options:
            rows: 5
        default_db_instance_size:
          title: Default DB Instance Size
          type: string
          description: You can specify a default and override per environment
          default: "db.t4g.medium"
          ui:options:
            rows: 5

    - title: Choose the component location
      required:
        - component
        - owner
      properties:
        component:
          title: Component
          type: string
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - component
#      properties:
#        repoUrl:
#          title: Repository Location
#          type: string
#          ui:field: RepoUrlPicker
#          ui:options:
#            allowedHosts:
#              - github.com
#            allowedOwners:
#              - TW-SEA-EMPC
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

  steps:
    - id: fetch-base
      name: Fetch golang starter template
      action: fetch:template
      input:
        url: ./content
        values:
          name : ${{ parameters.name | lower | replace(" ", "-") }}
          version: ${{ parameters.version }}
          db_engine_major_version: ${{ parameters.db_engine_major_version }}
          default_db_instance_size: ${{ parameters.default_db_instance_size }}
          component: ${{ parameters.component }}
          owner: ${{ parameters.owner }}
